version: '3'
services:
  front:
    container_name: node
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - "3000:3000"
    command: sh -c 'cd front && yarn start'
    volumes:
      - ./front:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data # ローカルにマウントしてデータの永続化
      - ./db/init:/docker-entrypoint-initdb.d # この配下にあるファイルを起動時に実行し初期設定・初期データの作成などを行う
  dbclient:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - ./dbclient/data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: erp_app@gmail.com
      PGADMIN_DEFAULT_PASSWORD: erp
    depends_on:
      - db
  api:
    image: eclipse-temurin
    ports:
      - "8080:8080"
    volumes:
      - ./api:/workspace
    working_dir: /workspace
    tty: true
    depends_on:
      - db
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: keycloak
    tty: true # CLI画面の操作をできるようにする
    stdin_open: true
    ports:
      - "18080:8080" # 8080は被りやすいので別のポートに設定
    volumes:
      - ./auth/data:/opt/keycloak/data # DB情報等が格納されます
    environment:
      KEYCLOAK_ADMIN: admin # 管理ユーザーIDを設定
      KEYCLOAK_ADMIN_PASSWORD: passwd # 管理ユーザーのパスワードを設定
    command:
      - start-dev # 開発モードで起動
